---
name: E2E テスト作成リクエスト
description: E2E テストを自動生成します
labels: ["test", "e2e"]
assignees: ["e2e-test-specialist"]
---

## 機能名
<!-- テスト対象の機能名を記載 -->

## テストシナリオ
<!-- 実装するテストシナリオをチェック -->
- [ ] 正常系: 成功パターン
- [ ] 異常系: エラーハンドリング
- [ ] 境界値テスト
- [ ] パフォーマンステスト

## 受け入れ条件
<!-- テストの受け入れ条件を記載 -->
- [ ] すべてのテストがローカルで成功すること
- [ ] Allure レポートが生成されること
- [ ] テストカバレッジが80%以上であること

## 実装パス
`frontend/tests/e2e/`

## 補足事項
<!-- 追加の要件や注意事項があれば記載 -->
