---
name: エラー解析リクエスト
description: エラーの解析と修正を行います
labels: ["bug", "error-analysis"]
assignees: []
---

## エラー種別
<!-- エラーの種別を選択 -->
- [ ] フロントエンドエラー
- [ ] バックエンドエラー
- [ ] データベースエラー
- [ ] パフォーマンス問題
- [ ] セキュリティ問題

## エラー概要
<!-- エラーの概要を記載 -->

## 再現手順
<!-- エラーを再現する手順を記載 -->
1. 
2. 
3. 

## 期待される動作
<!-- 本来どう動作すべきか -->

## 実際の動作
<!-- 実際にどう動作しているか -->

## エラーメッセージ・ログ
<!-- エラーメッセージやログを貼り付け -->
```
```

## 影響範囲
<!-- このエラーが影響する範囲 -->
- [ ] 重大（サービス全体に影響）
- [ ] 高（主要機能に影響）
- [ ] 中（一部機能に影響）
- [ ] 低（軽微な影響）

## 解析タスク
<!-- 解析に必要なタスク -->
- [ ] ログファイルの確認
- [ ] エラートレースの追跡
- [ ] パフォーマンスプロファイリング
- [ ] テストケースでの再現
- [ ] 原因特定
- [ ] 修正案の提示

## 受け入れ条件
<!-- 解析の受け入れ条件 -->
- [ ] エラーの根本原因を特定すること
- [ ] 再現手順を明確にすること
- [ ] 修正案を提示すること
- [ ] テストで修正を検証すること

## 実装パス
<!-- 関連するファイルパス -->

## 補足事項
<!-- 追加の情報や注意事項があれば記載 -->
