---
name: アプリ機能改修リクエスト
description: アプリの機能改修を行います
labels: ["enhancement", "feature"]
assignees: []
---

## 改修種別
<!-- 改修の種別を選択 -->
- [ ] UI/UX改善
- [ ] パフォーマンス改善
- [ ] 新機能追加
- [ ] リファクタリング

## 改修内容
<!-- 具体的な改修内容を記載 -->

## 改修対象
<!-- 改修対象の機能やコンポーネントを記載 -->

## 改修理由
<!-- なぜこの改修が必要か -->

## 期待される効果
<!-- この改修によって得られる効果 -->

## 実装タスク
<!-- 実装に必要なタスクをリストアップ -->
- [ ] 要件定義
- [ ] 設計
- [ ] 実装
- [ ] テスト
- [ ] ドキュメント更新

## 受け入れ条件
<!-- 改修の受け入れ条件 -->
- [ ] 既存機能に影響を与えないこと
- [ ] すべてのテストが成功すること
- [ ] コードレビューを完了すること
- [ ] ドキュメントを更新すること

## 実装パス
- フロントエンド: `frontend/src/`
- バックエンド: `backend/src/`

## 補足事項
<!-- 追加の要件や注意事項があれば記載 -->
