---
name: 操作マニュアル作成リクエスト
description: 操作マニュアルを作成します
labels: ["documentation", "manual"]
assignees: ["manual-specialist"]
---

## マニュアル種別
<!-- 作成するマニュアルの種別を選択 -->
- [ ] ユーザー向けマニュアル
- [ ] 管理者向けマニュアル
- [ ] 開発者向けマニュアル

## 対象機能
<!-- マニュアルを作成する対象機能を記載 -->

## 必要なセクション
<!-- 必要なセクションをチェック -->
- [ ] はじめに / 概要
- [ ] 基本操作
- [ ] 詳細機能
- [ ] トラブルシューティング
- [ ] FAQ
- [ ] 用語集

## 成果物
<!-- 期待する成果物 -->
- [ ] Markdown形式のマニュアル
- [ ] スクリーンショット
- [ ] 動画チュートリアル（オプション）

## 受け入れ条件
<!-- マニュアルの受け入れ条件 -->
- [ ] 初心者でも理解できる明確な説明
- [ ] スクリーンショットを適切に配置
- [ ] 目次とリンクが正しく機能すること

## 実装パス
`wiki/manual/`

## 補足事項
<!-- 追加の要件や注意事項があれば記載 -->
